version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    networks:
      - proxy
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
networks:
  proxy:
    name: proxy
    external: true
