version: '3'
services:
  gitea:
    image: gitea/gitea
    environment:
      - LOCAL_ROOT_URL=http://localhost:3000/
      # https://docs.gitea.io/en-us/config-cheat-sheet/
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__ENABLE_USER_HEATMAP=false
      - GITEA__service__ENABLE_TIMETRACKING=false
      - GITEA__repository__DEFAULT_BRANCH=master
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=true
    restart: unless-stopped
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "22:22"
volumes:
  gitea-data: