version: '3'
services:
  gitea:
    image: gitea/gitea
    environment:
      # https://docs.gitea.io/en-us/config-cheat-sheet/
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__server__HTTP_PORT=3030
      - GITEA__server__PROTOCOL=https
      - GITEA__server__DISABLE_SSH=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__ENABLE_USER_HEATMAP=false
      - GITEA__service__ENABLE_TIMETRACKING=false
      - GITEA__repository__DEFAULT_BRANCH=master
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=true
    restart: unless-stopped
    volumes:
      - gitea-data:/data
    ports:
      - "3030:3030"
volumes:
  gitea-data:
